import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import PDFDocument from "pdfkit";
import { Readable } from "stream";

export async function GET(
	request: NextRequest,
	{ params }: { params: Promise<{ id: string }> }
) {
	try {
		const user = await getCurrentUser();
		if (!user) {
			return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
		}

		const { id: sponsorId } = await params;
		
		// Fetch sponsor data
		const { getSponsorById } = await import("@/lib/sponsor-data");
		const sponsor = getSponsorById(user.whop_user_id, sponsorId);
		
		if (!sponsor) {
			return NextResponse.json(
				{ error: "Sponsor not found" },
				{ status: 404 }
			);
		}

		// Generate PDF invoice
		const doc = new PDFDocument({ margin: 50 });
		const chunks: Buffer[] = [];
		
		doc.on('data', (chunk) => chunks.push(chunk));

		// Header
		doc.fontSize(32).text('INVOICE', { align: 'left' });
		doc.fontSize(12).fillColor('#666666').text(`Invoice #${sponsor.id.slice(0, 8).toUpperCase()}`, { align: 'left' });
		doc.moveDown(2);

		// Bill To section
		doc.fontSize(14).fillColor('#666666').text('BILL TO:', { align: 'left' });
		doc.fontSize(14).fillColor('#000000').text(sponsor.brandName, { align: 'left' });
		if (sponsor.contactName) {
			doc.fontSize(12).fillColor('#000000').text(sponsor.contactName, { align: 'left' });
		}
		if (sponsor.contactEmail) {
			doc.fontSize(12).fillColor('#000000').text(sponsor.contactEmail, { align: 'left' });
		}
		doc.moveDown(1);

		// Invoice Details (right aligned)
		const invoiceDate = new Date().toLocaleDateString();
		const dueDate = sponsor.dueDate ? new Date(sponsor.dueDate).toLocaleDateString() : 'N/A';
		const paymentStatus = sponsor.paymentStatus.charAt(0).toUpperCase() + sponsor.paymentStatus.slice(1);
		
		doc.fontSize(14).fillColor('#666666').text('INVOICE DETAILS:', { align: 'right' });
		doc.fontSize(12).fillColor('#000000').text(`Date: ${invoiceDate}`, { align: 'right' });
		doc.fontSize(12).fillColor('#000000').text(`Due Date: ${dueDate}`, { align: 'right' });
		doc.fontSize(12).fillColor('#000000').text(`Status: ${paymentStatus}`, { align: 'right' });
		doc.moveDown(2);

		// Table header
		doc.fontSize(12).fillColor('#000000').text('Description', 50, doc.y);
		doc.text('Amount', 450, doc.y, { align: 'right' });
		doc.moveDown(0.5);
		doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
		doc.moveDown(0.5);

		// Table row
		const deliverables = sponsor.deliverables && sponsor.deliverables.length > 0 
			? sponsor.deliverables.join(', ') 
			: 'Sponsorship services';
		const amount = new Intl.NumberFormat('en-US', { style: 'currency', currency: sponsor.currency || 'USD' }).format(sponsor.rate);
		
		const descriptionY = doc.y;
		doc.fontSize(12).fillColor('#000000').text('Sponsorship Deal', 50, doc.y);
		doc.moveDown(0.3);
		doc.fontSize(10).fillColor('#666666').text(deliverables, 50, doc.y);
		if (sponsor.notes) {
			doc.moveDown(0.2);
			doc.fontSize(9).fillColor('#666666').text(sponsor.notes, 50, doc.y);
		}
		const descriptionEndY = doc.y;
		doc.fontSize(12).fillColor('#000000').text(amount, 450, descriptionY, { align: 'right' });
		doc.y = descriptionEndY;
		doc.moveDown(1);
		doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
		doc.moveDown(0.5);

		// Total row
		doc.fontSize(14).fillColor('#000000').text('Total:', 450, doc.y, { align: 'right' });
		doc.fontSize(14).fillColor('#000000').text(amount, 450, doc.y, { align: 'right' });
		doc.moveDown(3);

		// Footer
		doc.fontSize(10).fillColor('#666666').text('Thank you for your business!', { align: 'center' });
		doc.moveDown(0.5);
		doc.fontSize(9).fillColor('#666666').text(`Generated by CreatorOS on ${new Date().toLocaleString()}`, { align: 'center' });

		doc.end();

		// Wait for PDF to be generated
		const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
			doc.on('end', () => {
				resolve(Buffer.concat(chunks));
			});
			doc.on('error', reject);
		});

		return new NextResponse(pdfBuffer, {
			headers: {
				"Content-Type": "application/pdf",
				"Content-Disposition": `attachment; filename="invoice-${sponsor.brandName}-${new Date().toISOString().split("T")[0]}.pdf"`,
			},
		});
	} catch (error) {
		console.error("[Sponsor Export] Error:", error);
		return NextResponse.json(
			{ error: "Failed to export report" },
			{ status: 500 }
		);
	}
}

