import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";

export async function GET(
	request: NextRequest,
	{ params }: { params: Promise<{ id: string }> }
) {
	try {
		const user = await getCurrentUser();
		if (!user) {
			return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
		}

		const { id: sponsorId } = await params;
		
		// Fetch sponsor data
		const { getSponsorById } = await import("@/lib/sponsor-data");
		const sponsor = getSponsorById(user.whop_user_id, sponsorId);
		
		if (!sponsor) {
			return NextResponse.json(
				{ error: "Sponsor not found" },
				{ status: 404 }
			);
		}

		// Generate HTML invoice that can be viewed in browser or converted to PDF
		const invoiceHtml = `<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Invoice - ${sponsor.brandName}</title>
	<style>
		body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
		.header { border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
		.invoice-title { font-size: 32px; font-weight: bold; margin-bottom: 10px; }
		.invoice-details { display: flex; justify-content: space-between; margin-top: 30px; }
		.details-section { flex: 1; }
		.details-section h3 { margin-top: 0; color: #666; font-size: 14px; text-transform: uppercase; }
		.details-section p { margin: 5px 0; }
		.table { width: 100%; border-collapse: collapse; margin: 30px 0; }
		.table th { background: #f5f5f5; padding: 12px; text-align: left; border-bottom: 2px solid #ddd; }
		.table td { padding: 12px; border-bottom: 1px solid #eee; }
		.total-row { font-weight: bold; font-size: 18px; }
		.footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
	</style>
</head>
<body>
	<div class="header">
		<div class="invoice-title">INVOICE</div>
		<div style="color: #666;">Invoice #${sponsor.id.slice(0, 8).toUpperCase()}</div>
	</div>
	
	<div class="invoice-details">
		<div class="details-section">
			<h3>Bill To:</h3>
			<p><strong>${sponsor.brandName}</strong></p>
			${sponsor.contactName ? `<p>${sponsor.contactName}</p>` : ''}
			${sponsor.contactEmail ? `<p>${sponsor.contactEmail}</p>` : ''}
		</div>
		<div class="details-section" style="text-align: right;">
			<h3>Invoice Details:</h3>
			<p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
			<p><strong>Due Date:</strong> ${sponsor.dueDate ? new Date(sponsor.dueDate).toLocaleDateString() : 'N/A'}</p>
			<p><strong>Status:</strong> ${sponsor.paymentStatus.charAt(0).toUpperCase() + sponsor.paymentStatus.slice(1)}</p>
		</div>
	</div>
	
	<table class="table">
		<thead>
			<tr>
				<th>Description</th>
				<th style="text-align: right;">Amount</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<strong>Sponsorship Deal</strong><br>
					${sponsor.deliverables && sponsor.deliverables.length > 0 ? sponsor.deliverables.join(', ') : 'Sponsorship services'}
					${sponsor.notes ? `<br><small style="color: #666;">${sponsor.notes}</small>` : ''}
				</td>
				<td style="text-align: right;">${new Intl.NumberFormat('en-US', { style: 'currency', currency: sponsor.currency || 'USD' }).format(sponsor.rate)}</td>
			</tr>
			<tr class="total-row">
				<td style="text-align: right;">Total:</td>
				<td style="text-align: right;">${new Intl.NumberFormat('en-US', { style: 'currency', currency: sponsor.currency || 'USD' }).format(sponsor.rate)}</td>
			</tr>
		</tbody>
	</table>
	
	<div class="footer">
		<p>Thank you for your business!</p>
		<p>Generated by CreatorOS on ${new Date().toLocaleString()}</p>
	</div>
</body>
</html>`;

		return new NextResponse(invoiceHtml, {
			headers: {
				"Content-Type": "text/html",
				"Content-Disposition": `inline; filename="invoice-${sponsor.brandName}-${new Date().toISOString().split("T")[0]}.html"`,
			},
		});
	} catch (error) {
		console.error("[Sponsor Export] Error:", error);
		return NextResponse.json(
			{ error: "Failed to export report" },
			{ status: 500 }
		);
	}
}

